sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '5.1.0'
before_install:
  - npm i -g npm@^3.5.0
before_script:
  - npm prune
  - npm i -g gulp
script:
  - gulp build --release && gulp test
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
