sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '0.12'
before_install:
  - npm i -g npm@^2.0.0
  - npm i -g phantomjs
before_script:
  - npm prune
  - npm i -g gulp
script:
  - gulp build --release
  - gulp test
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
